skefor_config:
  base_url: "http://localhost:8001/v1"
  api_key: "EMPTY"
  model_name: "skefor"
  m: "3"

skeeva_config:
  base_url: "http://localhost:8002/v1"
  api_key: "EMPTY"
  model_name: "skeeva"

llm_call_config:
  base_url: ""
  api_key: ""
  model_name: ""

paths:
  dev_path: "./datasets/bird/dev/dev.json"
  databases_path: "./datasets/bird/dev/dev_databases/dev_databases"
  tables_path: "./datasets/bird/dev/dev_tables.json"
  output_path: "./outputs/pre_sql.json"